from .auth import auth_bp
from .dashboard import dashboard_bp
from .datasets import datasets_bp
from .detect import detect_bp
from .health import health_bp
from .logs import logs_bp
from .models import models_bp
from .reviews import reviews_bp
from .web import web_bp
